In [19]:
import pandas as pd
import torch
from torch.autograd import Variable
import torch.nn.functional as F
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [20]:
# read csv
# https://research.unsw.edu.au/projects/unsw-nb15-dataset
# According to the website above csv is wrongly saved, so I change the name
# The number of records in the training set is 175,341 records and the testing set is 82,332 records from the different types, attack and normal.
df = pd.read_csv('../../Data/UNSW_NB15_testing-set.csv')

In [21]:
# fix seed
# Pytorch
torch.manual_seed(0)
torch.cuda.manual_seed(0)

In [22]:
# nominal to numeric of data
# proto                 object
# service               object
# state                 object

# proto to numeric
# proto_mapping = {'xxx':2, 'xxx':1, 'xxx':0}
# data['proto'] = data['proto'].map(proto_mapping)

# one Hot Encoding is also applicable like using pandas dummies
df_processed = pd.get_dummies(df, columns=(['proto','service','state']))
 
# nominal to numeric of data
# attack_cat            object

# target to numeric
attack_cat_le = LabelEncoder()
df_processed['attack_cat'] = attack_cat_le.fit_transform(df_processed['attack_cat'])
pd.set_option("display.max_columns", 200)

df_processed.head(10)

id       dur  spkts  dpkts  sbytes  dbytes       rate  sttl  dttl  \
0   1  0.121478      6      4     258     172  74.087490   252   254   
1   2  0.649902     14     38     734   42014  78.473372    62   252   
2   3  1.623129      8     16     364   13186  14.170161    62   252   
3   4  1.681642     12     12     628     770  13.677108    62   252   
4   5  0.449454     10      6     534     268  33.373826   254   252   
5   6  0.380537     10      6     534     268  39.417980   254   252   
6   7  0.637109     10      8     534     354  26.683033   254   252   
7   8  0.521584     10      8     534     354  32.593026   254   252   
8   9  0.542905     10      8     534     354  31.313031   254   252   
9  10  0.258687     10      6     534     268  57.985135   254   252   

          sload          dload  sloss  dloss      sinpkt      dinpkt  \
0  14158.942380    8495.365234      0      0   24.295600    8.375000   
1   8395.112305  503571.312500      2     17   49.915000   15.432865   
2   1572.271851   60929.230470      1      6  231.875571  102.737203   
3   2740.178955    3358.622070      1      3  152.876547   90.235726   
4   8561.499023    3987.059814      2      1   47.750333   75.659602   
5  10112.025390    4709.134766      2      1   39.928778   52.241000   
6   6039.783203    3892.583740      2      1   68.267778   81.137711   
7   7377.527344    4754.747070      2      1   55.794000   66.054141   
8   7087.796387    4568.018555      2      1   60.210889   68.109000   
9  14875.120120    6927.291016      2      1   27.505111   39.106801   

           sjit          djit  swin       stcpb       dtcpb  dwin    tcprtt  \
0     30.177547     11.830604   255   621772692  2202533631   255  0.000000   
1     61.426934   1387.778330   255  1417884146  3077387971   255  0.000000   
2  17179.586860  11420.926230   255  2116150707  2963114973   255  0.111897   
3    259.080172   4991.784669   255  1107119177  1047442890   255  0.000000   
4   2415.837634    115.807000   255  2436137549  1977154190   255  0.128381   
5   2223.730342     82.550500   255  3984155503  1796040391   255  0.172934   
6   4286.828570    119.422719   255  1787309226  1767180493   255  0.143337   
7   3770.580726    118.962633   255   205985702   316006300   255  0.116615   
8   4060.625597    106.611547   255   884094874  3410317203   255  0.118584   
9   1413.686415     57.200395   255  3368447996   584859215   255  0.087934   

     synack    ackdat  smean  dmean  trans_depth  response_body_len  \
0  0.000000  0.000000     43     43            0                  0   
1  0.000000  0.000000     52   1106            0                  0   
2  0.061458  0.050439     46    824            0                  0   
3  0.000000  0.000000     52     64            0                  0   
4  0.071147  0.057234     53     45            0                  0   
5  0.119331  0.053603     53     45            0                  0   
6  0.069136  0.074201     53     44            0                  0   
7  0.059195  0.057420     53     44            0                  0   
8  0.066133  0.052451     53     44            0                  0   
9  0.063116  0.024818     53     45            0                  0   

   ct_srv_src  ct_state_ttl  ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  \
0           1             0           1                 1                 1   
1          43             1           1                 1                 1   
2           7             1           2                 1                 1   
3           1             1           2                 1                 1   
4          43             1           2                 2                 1   
5          43             1           2                 2                 1   
6          43             1           1                 1                 1   
7          43             1           3                 3                 1   
8          43             1           3               

In [23]:
df_train, df_test = train_test_split(df_processed, test_size=0.3, random_state=0)

In [24]:
#df_train.dtypes
df_train.shape

(122738, 197)

In [25]:
data_train = df_train.drop(['id', 'label', 'attack_cat'], axis=1)
label_train = df_train.iloc[:,-157]
data_train.head(10)

dur  spkts  dpkts  sbytes  dbytes          rate  sttl  dttl  \
41479   0.581798     10      6     588     268  2.578214e+01   254   252   
174119  0.000009      2      0     114       0  1.111111e+05   254     0   
39585   0.294033      8     12     424    8824  6.461860e+01    31    29   
23269   0.001059      2      2     146     178  2.832861e+03    31    29   
35227   1.433471     52     54    2934    3742  7.324878e+01    31    29   
157804  0.000003      2      0     114       0  3.333333e+05   254     0   
170646  1.434152     10      8     450     782  1.185370e+01    62   252   
102714  1.725872     10     10     798    1730  1.100893e+01    62   252   
138365  0.000001      2      0     114       0  1.000000e+06   254     0   
7840    0.528823     52     42   37372    3380  1.758622e+02    31    29   

               sload          dload  sloss  dloss      sinpkt      dinpkt  \
41479   7.287752e+03    3080.106689      2      1   61.319444   98.746602   
174119  5.066666e+07       0.000000      0      0    0.009000    0.000000   
39585   1.009411e+04  220084.140600      1      4   41.958143   26.683817   
23269   5.514636e+05  672332.375000      0      0    0.009000    0.008000   
35227   1.606171e+04   20498.496090     11     15   28.100333   27.030943   
157804  1.520000e+08       0.000000      0      0    0.003000    0.000000   
170646  2.259175e+03    3821.073242      1      2  159.350222  199.645141   
102714  3.332808e+03    7217.221191      2      2  191.755222  178.087328   
138365  4.560000e+08       0.000000      0      0    0.001000    0.000000   
7840    5.544993e+05   49922.183590     18      8   10.341843   12.885000   

                sjit         djit  swin       stcpb       dtcpb  dwin  \
41479    3292.453142   152.258547   255  1049982113  1627715135   255   
174119      0.000000     0.000000     0           0           0     0   
39585    2520.194735  1997.654762   255  1315021517  3724021920   255   
23269       0.000000     0.000000     0           0           0     0   
35227    1985.935789    62.207727   255  3873879927  1960497809   255   
157804      0.000000     0.000000     0           0           0     0   
170646  12787.230770   352.353250   255  1441315078  3613876827   255   
102714  11186.211620   297.156469   255  3941478131  3241465011   255   
138365      0.000000     0.000000     0           0           0     0   
7840      776.706018    25.271348   255  2558566450   461613287   255   

          tcprtt    synack    ackdat  smean  dmean  trans_depth  \
41479   0.166753  0.088056  0.078697     59     45            0   
174119  0.000000  0.000000  0.000000     57      0            0   
39585   0.000637  0.000507  0.000130     53    735            0   
23269   0.000000  0.000000  0.000000     73     89            0   
35227   0.000942  0.000827  0.000115     56     69            0   
157804  0.000000  0.000000  0.000000     57      0            0   
170646  0.106473  0.035793  0.070680     45     98            0   
102714  0.209789  0.123080  0.086709     80    173            1   
138365  0.000000  0.000000  0.000000     57      0            0   
7840    0.000669  0.000533  0.000136    719     80            0   

        response_body_len  ct_srv_src  ct_state_ttl  ct_dst_ltm  \
41479                   0           1             1           2   
174119                  0          31             2          15   
39585                   0           3             0          11   
23269                   0           4             0           2   
35227                   0           1             0           4   
157804                  0          14             2          12   
170646                  0           1             1           2   
102714                416           2             1           1   
138365                  0          18             2          16   
7840                    0           1             0           2   

        ct_src_dport_ltm  ct_dst_sport_ltm  ct_d

In [26]:
#min-max scaling
data_train_norm = (data_train - data_train.min()) / (data_train.max() - data_train.min())
data_train_norm = data_train_norm.fillna(0)

In [27]:
data_train_norm.shape
data_train_norm.head(10)

dur     spkts     dpkts    sbytes    dbytes      rate  \
41479   9.696635e-03  0.000936  0.000553  0.000042  0.000018  0.000026   
174119  1.500000e-07  0.000104  0.000000  0.000005  0.000000  0.111111   
39585   4.900551e-03  0.000728  0.001106  0.000029  0.000609  0.000065   
23269   1.765000e-05  0.000104  0.000184  0.000008  0.000012  0.002833   
35227   2.389119e-02  0.005304  0.004977  0.000223  0.000258  0.000073   
157804  5.000001e-08  0.000104  0.000000  0.000005  0.000000  0.333333   
170646  2.390254e-02  0.000936  0.000737  0.000031  0.000054  0.000012   
102714  2.876454e-02  0.000936  0.000922  0.000058  0.000119  0.000011   
138365  1.666667e-08  0.000104  0.000000  0.000005  0.000000  1.000000   
7840    8.813718e-03  0.005304  0.003871  0.002879  0.000233  0.000176   

            sttl      dttl         sload     dload     sloss     dloss  \
41479   0.996078  1.000000  1.217059e-06  0.000137  0.000416  0.000184   
174119  0.996078  0.000000  8.461366e-03  0.000000  0.000000  0.000000   
39585   0.121569  0.115079  1.685722e-06  0.009815  0.000208  0.000737   
23269   0.121569  0.115079  9.209479e-05  0.029984  0.000000  0.000000   
35227   0.121569  0.115079  2.682317e-06  0.000914  0.002290  0.002765   
157804  0.996078  0.000000  2.538410e-02  0.000000  0.000000  0.000000   
170646  0.243137  1.000000  3.772837e-07  0.000170  0.000208  0.000369   
102714  0.243137  1.000000  5.565811e-07  0.000322  0.000416  0.000369   
138365  0.996078  0.000000  7.615230e-02  0.000000  0.000000  0.000000   
7840    0.121569  0.115079  9.260175e-05  0.002226  0.003748  0.001475   

              sinpkt        dinpkt      sjit      djit  swin     stcpb  \
41479   7.267791e-04  1.741046e-03  0.002254  0.000530   1.0  0.244470   
174119  1.066711e-07  0.000000e+00  0.000000  0.000000   0.0  0.000000   
39585   4.973023e-04  4.704745e-04  0.001726  0.006953   1.0  0.306180   
23269   1.066711e-07  1.410516e-07  0.000000  0.000000   0.0  0.000000   
35227   3.330548e-04  4.765948e-04  0.001360  0.000217   1.0  0.901967   
157804  3.555703e-08  0.000000e+00  0.000000  0.000000   0.0  0.000000   
170646  1.888674e-03  3.520034e-03  0.008755  0.001226   1.0  0.335586   
102714  2.272749e-03  3.139938e-03  0.007659  0.001034   1.0  0.917706   
138365  1.185234e-08  0.000000e+00  0.000000  0.000000   0.0  0.000000   
7840    1.225751e-04  2.271813e-04  0.000532  0.000088   1.0  0.595718   

           dtcpb  dwin    tcprtt    synack    ackdat     smean     dmean  \
41479   0.378993   1.0  0.066201  0.041924  0.051744  0.021003  0.030864   
174119  0.000000   0.0  0.000000  0.000000  0.000000  0.019648  0.000000   
39585   0.867092   1.0  0.000253  0.000241  0.000085  0.016938  0.504115   
23269   0.000000   0.0  0.000000  0.000000  0.000000  0.030488  0.061043   
35227   0.456478   1.0  0.000374  0.000394  0.000076  0.018970  0.047325   
157804  0.000000   0.0  0.000000  0.000000  0.000000  0.019648  0.000000   
170646  0.841446   1.0  0.042270  0.017041  0.046473  0.011518  0.067215   
102714  0.754735   1.0  0.083286  0.058600  0.057012  0.035230  0.118656   
138365  0.000000   0.0  0.000000  0.000000  0.000000  0.019648  0.000000   
7840    0.107481   1.0  0.000266  0.000254  0.000089  0.468157  0.054870   

        trans_depth  response_body_len  ct_srv_src  ct_state_ttl  ct_dst_ltm  \
41479      0.000000           0.000000    0.000000      0.166667        0.02   
174119     0.000000           0.000000    0.483871      0.333333        0.28   
39585      0.000000           0.000000    0.032258      0.000000        0.20   
23269      0.000000           0.000000    0.048387      0.000000        0.02   
35227      0.000000           0.000000    0.000000      0.000000        0.06   
157804     0.000000           0.000000    0.209677      0.333333        0.22   
170646     0.000000           0.000000    0.000000      0.166667        0.02   
102714     0.005814           0.000063    0.016129      0.166667        0.00   
138365     0.00

In [28]:
train_X = torch.tensor(data_train_norm.values, dtype=torch.float32)
train_Y = torch.tensor(label_train.values, dtype=torch.long) 
train = TensorDataset(train_X, train_Y)

In [29]:
train_loader = DataLoader(train, batch_size=100, shuffle=True)
# drop_last = True

In [30]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(194, 850)
        self.fc2 = nn.Linear(850, 10)
        
    def forward(self, x):
        x = F.relu(self.fc1(x)) # ReLU: max(x, 0)
        x = self.fc2(x)
        # return F.log_softmax(x, dim=1)
        return x

model = Net()

In [31]:
print(torch.cuda.is_available())

True


In [32]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
print(device)

cuda


In [33]:
criterion = nn.CrossEntropyLoss()

In [34]:
#optimizer = torch.optim.SGD(model.parameters(), lr=0.03)
optimizer = torch.optim.Adam(model.parameters(), lr=0.03)

In [35]:
model.train()

Net(
  (fc1): Linear(in_features=194, out_features=850, bias=True)
  (fc2): Linear(in_features=850, out_features=10, bias=True)
)

In [36]:
#Training the machine learning model
loss_list=[]
for epoch in range(100): #learning 100 times
    #total_loss = 0
    model.train()
    for train_x, train_y in train_loader:
        train_x, train_y = Variable(train_x), Variable(train_y)
        train_x = train_x.to(device)
        train_y = train_y.to(device)
        optimizer.zero_grad()
        output = model(train_x)
        loss = criterion(output, train_y)
        loss.backward()
        optimizer.step()
        loss_list.append(loss.data)
        #print('epoch {}, loss {}'.format(epoch, loss.item()))

In [37]:
#Calculating correct_rate using the training data
pred_list = list()
test_y_list = list()
with torch.no_grad():
    model.eval()
    correct = 0
    for test_x, test_y in train_loader:
        test_y_list.extend(test_y.to('cpu').detach().numpy().tolist())
        test_x, test_y = Variable(test_x), Variable(test_y)
        test_x = test_x.to(device)
        test_y = test_y.to(device)
        output = model(test_x)
        pred = torch.max(output.data, 1)[1]
        #print(pred)
        pred_list.extend(pred.to('cpu').detach().numpy().tolist())
        correct += pred.eq(test_y.data.view_as(pred)).sum() 
    # correct_rate
    data_num = len(train_loader.dataset)
    print('correct _rate: {}/{} ({:.0f}%)\n'.format(correct, data_num, 100. * correct / data_num))

correct _rate: 97905/122738 (80%)



In [38]:
testdata = df_test.drop(['id', 'label', 'attack_cat'], axis=1)
testlabel = df_test.iloc[:,-157]

#min-max scaling
testdata_norm = (testdata - testdata.min()) / (testdata.max() - testdata.min())
testdata_norm = testdata_norm.fillna(0)

testdata_norm.head(10)

dur     spkts     dpkts    sbytes    dbytes      rate  \
87395   1.928715e-02  0.000948  0.000729  0.000074  0.000024  0.000015   
171525  6.666668e-08  0.000105  0.000000  0.000007  0.000000  0.250000   
100997  3.536851e-03  0.000527  0.000182  0.000076  0.000006  0.000033   
106304  1.500000e-07  0.000105  0.000000  0.000014  0.000000  0.111111   
170606  1.929705e-02  0.000948  0.000729  0.000040  0.000024  0.000015   
113031  1.333334e-07  0.000105  0.000000  0.000011  0.000000  0.125000   
70458   1.333334e-07  0.000105  0.000000  0.000014  0.000000  0.125000   
138025  1.500000e-07  0.000105  0.000000  0.000007  0.000000  0.111111   
135044  1.166667e-07  0.000105  0.000000  0.000007  0.000000  0.142857   
161530  5.000001e-08  0.000105  0.000000  0.000007  0.000000  0.333333   

            sttl      dttl         sload     dload     sloss     dloss  \
87395   0.996078  0.992126  1.139085e-06  0.000101  0.000421  0.000182   
171525  0.996078  0.000000  2.159091e-02  0.000000  0.000000  0.000000   
100997  0.243137  0.992126  5.868945e-06  0.000076  0.000421  0.000182   
106304  0.996078  0.000000  1.683502e-02  0.000000  0.000000  0.000000   
170606  0.996078  0.992126  6.202864e-07  0.000101  0.000421  0.000182   
113031  0.996078  0.000000  1.590909e-02  0.000000  0.000000  0.000000   
70458   0.996078  0.000000  1.893939e-02  0.000000  0.000000  0.000000   
138025  0.996078  0.000000  9.595959e-03  0.000000  0.000000  0.000000   
135044  0.996078  0.000000  1.233766e-02  0.000000  0.000000  0.000000   
161530  0.996078  0.000000  2.878788e-02  0.000000  0.000000  0.000000   

              sinpkt        dinpkt      sjit      djit  swin     stcpb  \
87395   2.038530e-03  2.877795e-03  0.004775  0.001031   1.0  0.486086   
171525  6.665565e-08  0.000000e+00  0.000000  0.000000   0.0  0.000000   
100997  7.072531e-04  1.311099e-07  0.001660  0.000000   1.0  0.344191   
106304  1.499752e-07  0.000000e+00  0.000000  0.000000   0.0  0.000000   
170606  2.096022e-03  2.815831e-03  0.005184  0.001000   1.0  0.798506   
113031  1.333113e-07  0.000000e+00  0.000000  0.000000   0.0  0.000000   
70458   1.333113e-07  0.000000e+00  0.000000  0.000000   0.0  0.000000   
138025  1.499752e-07  0.000000e+00  0.000000  0.000000   0.0  0.000000   
135044  1.166474e-07  0.000000e+00  0.000000  0.000000   0.0  0.000000   
161530  4.999173e-08  0.000000e+00  0.000000  0.000000   0.0  0.000000   

           dtcpb  dwin    tcprtt    synack    ackdat     smean     dmean  \
87395   0.606430   1.0  0.110113  0.057364  0.124639  0.046939  0.030178   
171525  0.000000   0.0  0.000000  0.000000  0.000000  0.019728  0.000000   
100997  0.097285   1.0  0.068261  0.055728  0.054527  0.092517  0.029492   
106304  0.000000   0.0  0.000000  0.000000  0.000000  0.048980  0.000000   
170606  0.387478   1.0  0.080952  0.074044  0.055696  0.017007  0.030178   
113031  0.000000   0.0  0.000000  0.000000  0.000000  0.038095  0.000000   
70458   0.000000   0.0  0.000000  0.000000  0.000000  0.048980  0.000000   
138025  0.000000   0.0  0.000000  0.000000  0.000000  0.019728  0.000000   
135044  0.000000   0.0  0.000000  0.000000  0.000000  0.019728  0.000000   
161530  0.000000   0.0  0.000000  0.000000  0.000000  0.019728  0.000000   

        trans_depth  response_body_len  ct_srv_src  ct_state_ttl  ct_dst_ltm  \
87395           0.0                0.0    0.000000      0.166667        0.00   
171525          0.0                0.0    0.209677      0.333333        0.28   
100997          0.0                0.0    0.096774      0.500000        0.06   
106304          0.0                0.0    0.048387      0.333333        0.04   
170606          0.2                0.0    0.016129      0.166667        0.00   
113031          0.0                0.0    0.016129      0.333333        0.00   
70458           0.0                0.0    0.032258      0.333333        0.02   
138025          0.0                0.0    0.419355      0.333333        0.54   
135044         

In [39]:
test_X = torch.tensor(testdata_norm.values, dtype=torch.float32)
test_Y = torch.tensor(testlabel.values, dtype=torch.long) 

test = TensorDataset(test_X, test_Y)
test_loader = DataLoader(test, batch_size=100)

In [40]:
with torch.no_grad():
    model.eval()
    correct = 0
    pred_list = list()
    test_y_list = list()
    for test_x, test_y in test_loader:
        test_x, test_y = Variable(test_x), Variable(test_y)
        test_y_list.extend(test_y.to('cpu').detach().numpy().tolist())
        test_x = test_x.to(device)
        test_y = test_y.to(device)
        output = model(test_x)
        pred = torch.max(output.data, 1)[1]
        pred_list.extend(pred.to('cpu').detach().numpy().tolist())
        correct += pred.eq(test_y.data.view_as(pred)).sum() 
    # correct_rate
    data_num = len(test_loader.dataset)
    print('correct _rate: {}/{} ({:.0f}%)\n'.format(correct, data_num, 100. * correct / data_num))

correct _rate: 41561/52603 (79%)



In [41]:
accuracy_score(test_y_list, pred_list)

0.790088017793662

In [42]:
precision_score(test_y_list, pred_list, average='macro')

0.6535103432324881

In [43]:
recall_score(test_y_list, pred_list, average='macro')

0.41574998296772536

In [44]:
f1_score(test_y_list, pred_list, average='macro')

0.4195439448168522

In [45]:
cm = confusion_matrix(test_y_list, pred_list, labels=[0,1,2,3,4,5,6,7,8,9])
print(cm)

[[   19     0    10   582     0     0     1     0     0     0]
 [    0    11    12   473    13     0     1    10     0     0]
 [    0    12   160  3420    73     1    14    18     1     0]
 [    0     8   244  9397   391     1    71    10     0     0]
 [    0     1     2   600  3386     0  1302    46     1     1]
 [    0     0    10   223    43 11838     2     5     0     0]
 [    0     0    29   347  1402     0 14895    19     0     0]
 [    0     0    11  1009   117     0   148  1841     0     0]
 [    0     2    14    93   132     0    23    59    14     0]
 [    0     0     0    28     7     0     0     0     0     0]]
